# Last table header row, minimum rows in statement
lastHeaderRow = 9
# Trailer rows count
trailerRows = 6
# First column number 
firstColumn = 2
# Name is used for format check
firstColumnName = Датасоздания
# Row with account number
accountRow = 4
# Column with account number
accountColumn = 6

# Column with turnover
turnoverColumn = 6

# Distance from last row for row with debit turnover
dtTurnoverRowDistance = 4
crTurnoverRowDistance = 3
# Distance from last row for row with outgoing rest
restRowDistance = 2

# Statement columns
opNumColumn = 7
opDateColumn = 3
ctrPartAccountColumn = 9
ctrPartNameColumn = 11
dtAmountColumn = 13
crAmountColumn = 14
purposeColumn = 16
