# Last table header row, minimum rows in statement
lastHeaderRow = 9
# Trailer rows count
trailerRows = 6
# First column number 
firstColumn = 2
# Column name is used for format check
firstColumnName = Датасоздания
# Name is used for incoming rest
incomingRestName = ВходящийОстаток:
# Name is used for outgoing rest
outgoingRestName = ИсходящийОстаток:
# Name is used for column positioning
opNumColumnName = №операции
# Row with account number
accountRow = 4
# Column with account number
accountColumn = 6

# Columns with headers and trailers positions
headerNameColumn = 1
headerValueColumn = 6
trailerNameColumn = 2
headerValueColumn = 6

# Distance from last row for row with debit turnover
dtTurnoverRowDistance = 4
crTurnoverRowDistance = 3
# Distance from last row for row with outgoing rest
restRowDistance = 2

# Statement columns
opNumColumn = 7
opDateColumn = 2
opValueColumn = 3
ctrPartAccountColumn = 9
ctrPartNameColumn = 11
dtAmountColumn = 13
crAmountColumn = 14
purposeColumn = 16

# Date format in sheet
dateFormat = dd.MM.yyyy
